spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/fastsns"
    username: root
    password: azzu8380!!
  jpa:
    hibernate:
      ddl-auto: create # Entity? db? ????? ???? ????
    show-sql: true
